### ISSUE TITLE
Hacktoberfest Contribuitions

### ISSUE THREAD

**Issue by murilo-arruda** [murilo-arruda/todo-list-node-cli#3]
Hello everyone!

You can open a Pull Request in this repository to contribuite to Hacktoberfest.

Things you can do:
1 - Improve the functions.
2 - Add a new feature (e.g.: accept multiples todo's files).
3 - Write a better documentation.

How:
1 - Fork the repository.
2 - Do the changes you want.
3 - Open a pull request.
4 - Wait for approval.

\* If you open a Pull Request with no information i will mark as invalid. So please do not try to get a "free" pull request here.

**Comment by asfo** [comment]
This was just a waste of time...
